version: "3.8"

services:
  playnow-frontend:
    build:
      context: .
      dockerfile: Dockerfile # Use the same Dockerfile
    working_dir: /usr/src/app
    command: npm run dev -- -H 0.0.0.0 # Development command
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Bind mounts for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped