import image1 from "@/public/images/user/user-01.png";
import image2 from "@/public/images/user/user-02.png";
import { Testimonial } from "@/types/testimonial";

export const testimonialData: Testimonial[] = [
  {
    id: 1,
    name: "JanTan",
    designation: "Founder @Mancom",
    image: image1,
    content: "Their support and service is unmatched. Truly a 5-star experience!",
    rating: 5,
    date: "April 15, 2025",
  },
  {
    id: 2,
    name: "Enan",
    designation: "Founder @Tubigan",
    image: image2,
    content: "Very satisfied with the overall experience. Will recommend!",
    rating: 4,
    date: "April 16, 2025",
  },
  {
    id: 3,
    name: "Klent",
    designation: "Happy Client",
    image: image1,
    content: "Smooth transaction, no issues at all!",
    rating: 4,
    date: "April 17, 2025",
  },
  {
    id: 4,
    name: "Mika",
    designation: "Business Owner",
    image: image2,
    content: "They really went above and beyond my expectations!",
    rating: 5,
    date: "April 18, 2025",
  },
  {
    id: 5,
    name: "Lara",
    designation: "Project Lead",
    image: image1,
    content: "Impressive results and great customer care.",
    rating: 4,
    date: "April 18, 2025",
  },
  {
    id: 6,
    name: "Zed",
    designation: "Entrepreneur",
    image: image2,
    content: "Reliable and efficient. Can’t ask for more!",
    rating: 5,
    date: "April 19, 2025",
  },
  {
    id: 7,
    name: "Toni",
    designation: "Client",
    image: image1,
    content: "You guys rock! Keep it up!",
    rating: 5,
    date: "April 20, 2025",
  },
  {
    id: 8,
    name: "Ben",
    designation: "Small Biz Owner",
    image: image2,
    content: "Great value for money. Highly recommended.",
    rating: 4,
    date: "April 21, 2025",
  },
  {
    id: 9,
    name: "Faye",
    designation: "Regular User",
    image: image1,
    content: "Everything works perfectly! So glad I found this.",
    rating: 5,
    date: "April 22, 2025",
  },
];
