import { Merchant } from "@/types/merchant";

const merchantData: Merchant[] = [
  {
    id: 1,
    name: "Merchant 1",
    category: "Featured",
    image: "/images/merchant/1.png",
    title: "Featured Merchant 1",
    description: "This is a featured merchant.",
    price: "₱100.00",
    rating: 4.5,
    address: "123 Main St",
    numberOfCoupons: 10,
    isFeatured: true,
  },
  {
    id: 2,
    name: "Merchant 2",
    category: "Featured",
    image: "/images/merchant/2.png",
    title: "Featured Merchant 2",
    description: "This is another featured merchant.",
    price: "₱150.00",
    rating: 4.0,
    address: "456 Elm St",
    numberOfCoupons: 5,
    isFeatured: true,
  },
  {
    id: 3,
    name: "Merchant 3",
    category: "Hottest",
    image: "/images/merchant/3.png",
    title: "Hottest Merchant 1",
    description: "This is a hottest merchant.",
    price: "₱200.00",
    rating: 4.8,
    address: "789 Oak St",
    numberOfCoupons: 8,
    isFeatured: false,
  },
  {
    id: 4,
    name: "Merchant 4",
    category: "Hottest",
    image: "/images/merchant/4.png",
    title: "Hottest Merchant 2",
    description: "This is another hottest merchant.",
    price: "₱250.00",
    rating: 4.2,
    address: "321 Pine St",
    numberOfCoupons: 12,
    isFeatured: false,
  },
  {
    id: 5,
    name: "Merchant 5",
    category: "New",
    image: "/images/merchant/5.png",
    title: "New Merchant 1",
    description: "This is a new merchant.",
    price: "₱300.00",
    rating: 4.7,
    address: "654 Maple St",
    numberOfCoupons: 15,
    isFeatured: false,
  },
  {
    id: 6,
    name: "Merchant 6",
    category: "New",
    image: "/images/merchant/6.png",
    title: "New Merchant 2",
    description: "This is another new merchant.",
    price: "₱350.00",

    rating: 4.3,
    address: "987 Birch St",
    numberOfCoupons: 7,
    isFeatured: false,
  },
  {
    id: 7,
    name: "Merchant 7",
    category: "All",
    image: "/images/merchant/1.png",
    title: "All Merchant 1",
    description: "This is a general merchant.",
    price: "₱400.00",
    rating: 4.6,
    address: "159 Cedar St",
    numberOfCoupons: 9,
    isFeatured: false,
  },
  {
    id: 8,
    name: "Merchant 8",
    category: "All",
    image: "/images/merchant/2.png",
    title: "All Merchant 2",
    description: "This is another general merchant.",
    price: "₱450.00",
    rating: 4.1,
    address: "753 Walnut St",
    numberOfCoupons: 6,
    isFeatured: false,
  },
  {
    id: 9,
    name: "Merchant 9",
    category: "Featured",
    image: "/images/merchant/3.png",
    title: "Featured Merchant 3",
    description: "This is a third featured merchant.",
    price: "₱120.00",
    rating: 4.9,
    address: "852 Spruce St",
    numberOfCoupons: 11,
    isFeatured: true,
  },
  {
    id: 10,
    name: "Merchant 10",
    category: "Hottest",
    image: "/images/merchant/4.png",
    title: "Hottest Merchant 3",
    description: "This is a third hottest merchant.",
    price: "₱220.00",
    rating: 4.4,
    address: "951 Fir St",
    numberOfCoupons: 13,
    isFeatured: false,
  },
  {
    id: 11,
    name: "Merchant 11",
    category: "New",
    image: "/images/merchant/5.png",
    title: "New Merchant 3",
    description: "This is a third new merchant.",
    price: "₱330.00",
    rating: 4.5,
    address: "753 Palm St",
    numberOfCoupons: 14,
    isFeatured: false,
  },
  {
    id: 12,
    name: "Merchant 12",
    category: "New",
    image: "/images/merchant/6.png",
    title: "New Merchant 2",
    description: "This is fourth new merchant.",
    price: "₱630.00",
    rating: 4.3,
    address: "159 Cypress St",
    numberOfCoupons: 10,
    isFeatured: false,
  },
  {
    id: 13,
    name: "Merchant 13",
    category: "New",
    image: "/images/merchant/1.png",
    title: "New Merchant 1",
    description: "This is a third new merchant.",
    price: "₱730.00",
    rating: 4.2,
    address: "357 Redwood St",
    numberOfCoupons: 8,
    isFeatured: false,
  },
];

export default merchantData;
